<?php

namespace Database\Seeders;

use App\Models\Business;
use App\Models\PermissionModel;
use App\Models\Role;
use Illuminate\Database\Seeder;

class DefaultRolesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach (Business::all() as $business){
            $business_id = $business->id;
            $defaultRoles = [
                [
                    'name' => 'Admin',
                    'business_id' => $business_id,
                    'permissions' => PermissionModel::whereIn('name', [
                        'business-dashboard',
                        'order-list',
                        'order-edit',
                        'order-view',
                        'order-invoice-generate',
                        'order-invoice',
                        'invoice-print',
                        'order-payment',
                        'order-status',
                        'order-bulk-status',
                        'order-cancel',
                        'order-refund',
                        'reports-simple',
                        'reports-advanced',
                        'customer-list',
                        'customer-create',
                        'customer-edit',
                        'customer-view',
                        'customer-delete',
                        'customer-status',
                        'customer-bulk-status',
                        'customer-bulk-delete',
                        'product-list',
                        'product-create',
                        'product-edit',
                        'product-delete',
                        'product-view',
                        'product-status',
                        'product-bulk-status',
                        'product-bulk-delete',
                        'discount-list',
                        'discount-create',
                        'discount-edit',
                        'discount-delete',
                        'discount-view',
                        'discount-status',
                        'discount-bulk-status',
                        'discount-bulk-delete',
                        'store-info',
                        'eid-and-trade-license',
                        'store-create',
                        'account-info',
                        'notification-setting',
                        'bank-details',
                        'checkout-setting',
                        'payment-setting',
                        'page-list',
                        'page-create',
                        'page-edit',
                        'page-view',
                        'page-delete',
                        'page-status',
                        'page-bulk-status',
                        'page-bulk-delete',
                        'brand-list',
                        'brand-create',
                        'brand-edit',
                        'brand-view',
                        'brand-delete',
                        'brand-status',
                        'brand-bulk-status',
                        'brand-bulk-delete',
                        'category-list',
                        'category-create',
                        'category-edit',
                        'category-view',
                        'category-delete',
                        'category-status',
                        'category-bulk-status',
                        'category-bulk-delete',
                        'addon-list',
                        'addon-create',
                        'addon-edit',
                        'addon-view',
                        'addon-delete',
                        'addon-status',
                        'addon-bulk-status',
                        'addon-bulk-delete',
                        'shipping-general',
                        'shipping-areas',
                        'zone-list',
                        'zone-create',
                        'zone-edit',
                        'zone-delete',
                        'zone-areas',
                        'user-list',
                        'user-create',
                        'user-edit',
                        'user-view',
                        'user-delete',
                        'user-status',
                        'user-bulk-status',
                        'user-bulk-delete',
                        'role-list',
                        'role-create',
                        'role-edit',
                        'role-view',
                        'role-delete',
                        'role-status',
                    ])->whereIsBusiness(1)->get()->pluck('id')
                ],
                [
                    'name' => 'Manager',
                    'business_id' => $business_id,
                    'permissions' => PermissionModel::whereIn('name', [
                        'business-dashboard',
                        'order-list',
                        'order-edit',
                        'order-view',
                        'order-invoice-generate',
                        'order-invoice',
                        'invoice-print',
                        'order-payment',
                        'order-status',
                        'order-bulk-status',
                        'order-cancel',
                        'order-refund',
                        'reports-simple',
                        'customer-list',
                        'customer-create',
                        'customer-edit',
                        'customer-view',
                        'customer-status',
                        'customer-bulk-status',
                        'product-list',
                        'product-create',
                        'product-edit',
                        'product-delete',
                        'product-view',
                        'product-status',
                        'product-bulk-status',
                        'product-bulk-delete',
                        'discount-list',
                        'discount-create',
                        'discount-edit',
                        'discount-view',
                        'discount-status',
                        'discount-bulk-status',
                        'store-info',
                        'notification-setting',
                        'checkout-setting',
                        'page-list',
                        'page-create',
                        'page-edit',
                        'page-view',
                        'page-status',
                        'page-bulk-status',
                        'brand-list',
                        'brand-create',
                        'brand-edit',
                        'brand-view',
                        'brand-status',
                        'brand-bulk-status',
                        'category-list',
                        'category-create',
                        'category-edit',
                        'category-view',
                        'category-status',
                        'category-bulk-status',
                        'addon-list',
                        'addon-create',
                        'addon-edit',
                        'addon-view',
                        'addon-status',
                        'addon-bulk-status',
                        'shipping-general',
                        'shipping-areas',
                        'zone-list',
                        'zone-create',
                        'zone-edit',
                        'zone-delete',
                        'zone-areas',
                        'role-list',
                        'role-create',
                        'role-edit',
                        'role-view',
                        'role-status',
                    ])->whereIsBusiness(1)->get()->pluck('id')
                ],
                [
                    'name' => 'Supervisor',
                    'business_id' => $business_id,
                    'permissions' => PermissionModel::whereIn('name', [
                        'business-dashboard',
                        'order-list',
                        'order-view',
                        'order-invoice-generate',
                        'order-invoice',
                        'invoice-print',
                        'order-payment',
                        'order-status',
                        'order-bulk-status',
                        'order-cancel',
                        'customer-list',
                        'customer-create',
                        'customer-view',
                        'customer-status',
                        'customer-bulk-status',
                        'product-list',
                        'product-create',
                        'product-edit',
                        'discount-list',
                        'discount-view',
                        'discount-status',
                        'discount-bulk-status',
                        'checkout-setting',
                        'page-list',
                        'page-view',
                        'page-status',
                        'page-bulk-status',
                        'brand-list',
                        'brand-create',
                        'brand-view',
                        'brand-status',
                        'brand-bulk-status',
                        'category-list',
                        'category-create',
                        'category-view',
                        'category-status',
                        'category-bulk-status',
                        'addon-list',
                        'addon-create',
                        'addon-view',
                        'addon-status',
                        'addon-bulk-status',
                        'shipping-general',
                        'shipping-areas',
                        'zone-list',
                        'zone-create',
                        'zone-areas'
                    ])->whereIsBusiness(1)->get()->pluck('id')
                ],
                [
                    'name' => 'Staff',
                    'business_id' => $business_id,
                    'permissions' => PermissionModel::whereIn('name', [
                        'business-dashboard',
                        'order-list',
                        'order-view',
                        'order-status',
                        'order-bulk-status',
                        'product-list',
                        'product-status',
                        'product-bulk-status',
                        'product-create',
                        'product-edit',
                        'discount-list',
                        'page-list',
                        'page-view',
                        'brand-list',
                        'category-list',
                        'addon-list',
                        'shipping-general',
                        'shipping-areas',
                        'zone-list',
                        'zone-areas'
                    ])->whereIsBusiness(1)->get()->pluck('id')
                ]
            ];

            foreach ($defaultRoles as $role) {
                $existRole = Role::whereName($role['name'])->whereBusinessId($business_id)->first();
                if (!$existRole){
                    $newRole = new Role();
                    $newRole->name = $role['name'];
                    $newRole->is_business = 1;
                    $newRole->guard_name = 'web';
                    $newRole->business_id = $business_id;
                    $newRole->save();
                    $newRole->syncPermissions($role['permissions']);
                }else{
                    $existRole->syncPermissions($role['permissions']);
                }
            }
        }
    }
}
