<?php

namespace App\Constants;

interface AppConstants
{

    CONST PAGINATE_SMALL = 5;
    CONST PAGINATE_LARGE = 10;

    CONST PAGINATE = 4;
    CONST ADDRESS_TYPE_SHIPPING = 1;
    CONST ADDRESS_TYPE_BILLING = 2;

    CONST PAYMENT_METHOD = 1;

    CONST PAYMENT_COD = 1;
    CONST PAYMENT_PAYTABS = 2;
    CONST PAYMENT_CCAVENUE = 3;
    const PAYMENT_STRIPE = 4;

    CONST ORDER_STATUS_TYPE_PAYMENT = 1;
    CONST ORDER_STATUS_TYPE_ORDER = 2;
    CONST ORDER_STATUS_TYPE_FULFILMENT = 3;


    CONST PLAN_OPTION_WEBSITE = 'website';
    CONST PLAN_OPTION_PAYMENTS ='payments';
    CONST PLAN_OPTION_COMMISSION_ONLINE ='commission_online';
    CONST PLAN_OPTION_COMMISSION_SALE ='commission_all_sale';
    CONST PLAN_OPTION_ORDER_TYPE ='order_type';
    CONST PLAN_OPTION_ANALYTICS ='analytics';
    CONST PLAN_OPTION_STAFF ='staff';
    CONST PLAN_OPTION_STORES ='stores';
    CONST PLAN_OPTION_PRODUCTS ='products';
    CONST PLAN_OPTION_UNLIMITED_PRODUCTS ='unlimited_products';
    CONST PLAN_OPTION_DOMAIN_LINK ='domain_link';
    CONST PLAN_OPTION_MOBILE_APP ='mobile_app';
    CONST PLAN_OPTION_FREE_DAYS ='free_days';
    CONST PLAN_OPTION_INCLUDED_PLAN ='includes_plan';
    CONST PLAN_OPTION_COUPON_CODE ='coupon_code';
    CONST PLAN_OPTION_CHANGE_PAYMENT_METHOD ='change_payment_method';
    CONST PLAN_OPTION_DELIVERY_SERVICE_INTEGRATION ='delivery_service_integration';
    CONST PLAN_OPTION_RAISE_INVOICE ='raise_invoice';
    CONST PLAN_OPTION_CUSTOMER_LISTING ='customer_listing';
    CONST PLAN_OPTION_CUSTOM_EMAIL_TEMP ='custom_email_template';
    CONST PLAN_OPTION_SMS_MANAGER ='sms_manager';


    CONST ARAMEX = 'ARM';
    CONST OWN = 'OWN';

    CONST DELIVERY_OWN = 0;
    CONST DELIVERY_COMPANY_ARAMEX = 1;

    CONST ARAMEX_SHIPPING = 1;
    CONST ARAMEX_PICKUP = 2;
    CONST ARAMEX_LABEL_PRINT = 3;

    CONST SUBSCRIPTION_PAYMENT = 1;
}
